export const postTypes = {
    SET_POST_DATA: "SET_POST_DATA",
    GET_SINGLE_POST: "GET_SINGLE_POST",
    GET_ALL_POSTS: "GET_ALL_POSTS",
    SAVE_SINGLE_POST: "SAVE_SINGLE_POST",
    SHOW_POST_DATA: "SHOW_POST_DATA",
    ERROR_MESSAGE: "ERROR_MESSAGE"
}

export const userTypes = {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_SINGLE_USER: "GET_SINGLE_USER",
    SET_USERS_DATA: "SET_USERS_DATA"
}